"""Generic language signals for classifying patch owners vs support context."""

SUPPORT_CONTEXT_TERMS = (
    "after the fact",
    "blast radius",
    "can reduce",
    "cannot prevent",
    "confirming",
    "confirms",
    "consequence",
    "downstream",
    "impact",
    "later",
    "mitigation",
    "monitoring",
    "not prevent",
    "not sufficient",
    "observable",
    "observability",
    "presentation",
    "propagate",
    "propagates",
    "rather than",
    "reduce but not eliminate",
    "resulting",
    "safeguard",
    "secondary",
    "surface",
    "surfaces",
    "supporting",
    "does not prevent",
)

DIRECT_CHANGE_TERMS = (
    "add",
    "change",
    "enforce",
    "guard",
    "implement",
    "introduce",
    "link",
    "merge",
    "modify",
    "patch",
    "reject",
    "update",
    "validate",
    "version",
)

PATCH_OWNER_TERMS = (
    "allows",
    "before",
    "bypass",
    "change",
    "condition",
    "create",
    "creates",
    "detection",
    "direct entry point",
    "does not",
    "fails to",
    "faulty",
    "fix",
    "guard",
    "identity",
    "incorrect",
    "instead of",
    "key",
    "missing",
    "prevent",
    "primary",
    "reject",
    "root cause",
    "state",
    "update",
    "use",
    "uses",
    "validate",
    "wrong",
)

PATCH_OWNER_OVERRIDE_TERMS = (
    "allows",
    "bypass",
    "direct entry point",
    "fails to",
    "faulty",
    "incorrect",
    "instead of",
    "missing",
    "primary",
    "wrong",
)

DIRECT_OWNER_FIELDS = {
    "root_cause",
    "immediate_fix",
    "long_term_prevention",
    "solution_summary",
    "solution_step",
}

VALIDATION_STEP_PREFIXES = (
    "run ",
    "validate ",
    "verify ",
    "confirm ",
    "reproduce ",
    "test ",
    "monitor ",
)

VALIDATION_STEP_TERMS = (
    "test",
    "validation",
    "verify",
    "reproduce",
    "confirm",
    "monitoring",
)
